[tool.poetry]
name = "snakemake-storage-plugin-rsync"
version = "0.2.0"
description = ""
authors = [ "Per Unneberg <per.unneberg@scilifelab.se>",]
readme = "README.md"
repository = "https://github.com/percyfal/snakemake-storage-plugin-rsync"
documentation = "https://github.com/percyfal/snakemake-storage-plugin-rsync"

[tool.poetry.dependencies]
python = "^3.12"
snakemake-interface-common = "^1.17.4"
snakemake-interface-storage-plugins = "^4.1.0"
sysrsync = "^1.1.1"


[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
flake8 = "^7.1.1"
coverage = "^7.6.10"
pytest = "^8.3.4"
snakemake = "^9.0.0"

[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"
